# Generated by Django 5.2.3 on 2025-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_company',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
