# Generated by Django 5.2.3 on 2025-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_remove_profile_is_company_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
