# Generated by Django 5.2.3 on 2025-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_remove_profile_role_profile_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_company',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer')], default='jobseeker', max_length=20),
        ),
    ]
