# Generated by Django 5.2.3 on 2025-07-21 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0012_application_status_alter_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
