# Generated by Django 5.2.3 on 2025-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0013_jobpost_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
