# Generated by Django 5.2.3 on 2025-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0014_alter_jobpost_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
