# Generated by Django 5.2.3 on 2025-11-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0015_companyprofile_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='location',
            new_name='work_type',
        ),
    ]
