# Generated by Django 5.2.3 on 2025-11-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0016_rename_location_jobpost_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
